export type { LanguageDetectorResult } from './detectLanguage.js';
export { detectLanguage } from './detectLanguage.js';
export type { ProofreaderCorrection, ProofreaderResult, ProofreadOptions } from './proofread.js';
export { proofread } from './proofread.js';
export type { RewriteOptions } from './rewrite.js';
export { rewrite, rewriteStream } from './rewrite.js';
export type { SummarizeOptions } from './summarize.js';
export { summarize, summarizeStream } from './summarize.js';
export type { TranslateOptions } from './translate.js';
export { isTranslationAvailable, translate, translateStream } from './translate.js';
export type { WriteOptions } from './write.js';
export { write, writeStream } from './write.js';
